// Code generated by MockGen. DO NOT EDIT.
// Source: go/base/workflowclient/interface/workflowclient.go

// Package workflowclientInterfacemocks is a generated GoMock package.
package workflowclientInterfacemocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	interface0 "github.com/michelangelo-ai/michelangelo/go/base/workflowclient/interface"
)

// MockWorkflowClient is a mock of WorkflowClient interface.
type MockWorkflowClient struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowClientMockRecorder
}

// MockWorkflowClientMockRecorder is the mock recorder for MockWorkflowClient.
type MockWorkflowClientMockRecorder struct {
	mock *MockWorkflowClient
}

// NewMockWorkflowClient creates a new mock instance.
func NewMockWorkflowClient(ctrl *gomock.Controller) *MockWorkflowClient {
	mock := &MockWorkflowClient{ctrl: ctrl}
	mock.recorder = &MockWorkflowClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowClient) EXPECT() *MockWorkflowClientMockRecorder {
	return m.recorder
}

// CancelWorkflow mocks base method.
func (m *MockWorkflowClient) CancelWorkflow(ctx context.Context, workflowID, runID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelWorkflow", ctx, workflowID, runID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelWorkflow indicates an expected call of CancelWorkflow.
func (mr *MockWorkflowClientMockRecorder) CancelWorkflow(ctx, workflowID, runID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelWorkflow", reflect.TypeOf((*MockWorkflowClient)(nil).CancelWorkflow), ctx, workflowID, runID, reason)
}

// GetActivityTaskCompletedEventType mocks base method.
func (m *MockWorkflowClient) GetActivityTaskCompletedEventType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityTaskCompletedEventType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetActivityTaskCompletedEventType indicates an expected call of GetActivityTaskCompletedEventType.
func (mr *MockWorkflowClientMockRecorder) GetActivityTaskCompletedEventType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityTaskCompletedEventType", reflect.TypeOf((*MockWorkflowClient)(nil).GetActivityTaskCompletedEventType))
}

// GetActivityTaskScheduledEventType mocks base method.
func (m *MockWorkflowClient) GetActivityTaskScheduledEventType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityTaskScheduledEventType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetActivityTaskScheduledEventType indicates an expected call of GetActivityTaskScheduledEventType.
func (mr *MockWorkflowClientMockRecorder) GetActivityTaskScheduledEventType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityTaskScheduledEventType", reflect.TypeOf((*MockWorkflowClient)(nil).GetActivityTaskScheduledEventType))
}

// GetDecisionTaskCompletedEventType mocks base method.
func (m *MockWorkflowClient) GetDecisionTaskCompletedEventType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecisionTaskCompletedEventType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDecisionTaskCompletedEventType indicates an expected call of GetDecisionTaskCompletedEventType.
func (mr *MockWorkflowClientMockRecorder) GetDecisionTaskCompletedEventType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecisionTaskCompletedEventType", reflect.TypeOf((*MockWorkflowClient)(nil).GetDecisionTaskCompletedEventType))
}

// GetDomain mocks base method.
func (m *MockWorkflowClient) GetDomain() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomain")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDomain indicates an expected call of GetDomain.
func (mr *MockWorkflowClientMockRecorder) GetDomain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockWorkflowClient)(nil).GetDomain))
}

// GetProvider mocks base method.
func (m *MockWorkflowClient) GetProvider() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockWorkflowClientMockRecorder) GetProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockWorkflowClient)(nil).GetProvider))
}

// GetWorkflowExecutionHistory mocks base method.
func (m *MockWorkflowClient) GetWorkflowExecutionHistory(ctx context.Context, workflowID, runID string, pageToken []byte, pageSize int32) (*interface0.WorkflowHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowExecutionHistory", ctx, workflowID, runID, pageToken, pageSize)
	ret0, _ := ret[0].(*interface0.WorkflowHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowExecutionHistory indicates an expected call of GetWorkflowExecutionHistory.
func (mr *MockWorkflowClientMockRecorder) GetWorkflowExecutionHistory(ctx, workflowID, runID, pageToken, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowExecutionHistory", reflect.TypeOf((*MockWorkflowClient)(nil).GetWorkflowExecutionHistory), ctx, workflowID, runID, pageToken, pageSize)
}

// GetWorkflowExecutionInfo mocks base method.
func (m *MockWorkflowClient) GetWorkflowExecutionInfo(ctx context.Context, workflowID, runID string) (*interface0.WorkflowExecutionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowExecutionInfo", ctx, workflowID, runID)
	ret0, _ := ret[0].(*interface0.WorkflowExecutionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowExecutionInfo indicates an expected call of GetWorkflowExecutionInfo.
func (mr *MockWorkflowClientMockRecorder) GetWorkflowExecutionInfo(ctx, workflowID, runID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowExecutionInfo", reflect.TypeOf((*MockWorkflowClient)(nil).GetWorkflowExecutionInfo), ctx, workflowID, runID)
}

// ListOpenWorkflow mocks base method.
func (m *MockWorkflowClient) ListOpenWorkflow(ctx context.Context, request interface0.ListOpenWorkflowExecutionsRequest) (*interface0.ListOpenWorkflowExecutionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenWorkflow", ctx, request)
	ret0, _ := ret[0].(*interface0.ListOpenWorkflowExecutionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOpenWorkflow indicates an expected call of ListOpenWorkflow.
func (mr *MockWorkflowClientMockRecorder) ListOpenWorkflow(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenWorkflow", reflect.TypeOf((*MockWorkflowClient)(nil).ListOpenWorkflow), ctx, request)
}

// QueryWorkflow mocks base method.
func (m *MockWorkflowClient) QueryWorkflow(ctx context.Context, workflowID, runID, queryHandlerKey string, queryResult any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWorkflow", ctx, workflowID, runID, queryHandlerKey, queryResult)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryWorkflow indicates an expected call of QueryWorkflow.
func (mr *MockWorkflowClientMockRecorder) QueryWorkflow(ctx, workflowID, runID, queryHandlerKey, queryResult interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWorkflow", reflect.TypeOf((*MockWorkflowClient)(nil).QueryWorkflow), ctx, workflowID, runID, queryHandlerKey, queryResult)
}

// ResetWorkflow mocks base method.
func (m *MockWorkflowClient) ResetWorkflow(ctx context.Context, options interface0.ResetWorkflowOptions) (*interface0.WorkflowExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetWorkflow", ctx, options)
	ret0, _ := ret[0].(*interface0.WorkflowExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetWorkflow indicates an expected call of ResetWorkflow.
func (mr *MockWorkflowClientMockRecorder) ResetWorkflow(ctx, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetWorkflow", reflect.TypeOf((*MockWorkflowClient)(nil).ResetWorkflow), ctx, options)
}

// StartWorkflow mocks base method.
func (m *MockWorkflowClient) StartWorkflow(ctx context.Context, options interface0.StartWorkflowOptions, workflowName string, args ...interface{}) (*interface0.WorkflowExecution, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, options, workflowName}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartWorkflow", varargs...)
	ret0, _ := ret[0].(*interface0.WorkflowExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartWorkflow indicates an expected call of StartWorkflow.
func (mr *MockWorkflowClientMockRecorder) StartWorkflow(ctx, options, workflowName interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, options, workflowName}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWorkflow", reflect.TypeOf((*MockWorkflowClient)(nil).StartWorkflow), varargs...)
}

// TerminateWorkflow mocks base method.
func (m *MockWorkflowClient) TerminateWorkflow(ctx context.Context, workflowID, runID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateWorkflow", ctx, workflowID, runID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateWorkflow indicates an expected call of TerminateWorkflow.
func (mr *MockWorkflowClientMockRecorder) TerminateWorkflow(ctx, workflowID, runID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateWorkflow", reflect.TypeOf((*MockWorkflowClient)(nil).TerminateWorkflow), ctx, workflowID, runID, reason)
}

// PauseTrigger mocks base method.
func (m *MockWorkflowClient) PauseTrigger(ctx context.Context, workflowID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseTrigger", ctx, workflowID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseTrigger indicates an expected call of PauseTrigger.
func (mr *MockWorkflowClientMockRecorder) PauseTrigger(ctx, workflowID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseTrigger", reflect.TypeOf((*MockWorkflowClient)(nil).PauseTrigger), ctx, workflowID)
}

// UnpauseTrigger mocks base method.
func (m *MockWorkflowClient) UnpauseTrigger(ctx context.Context, workflowID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpauseTrigger", ctx, workflowID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpauseTrigger indicates an expected call of UnpauseTrigger.
func (mr *MockWorkflowClientMockRecorder) UnpauseTrigger(ctx, workflowID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpauseTrigger", reflect.TypeOf((*MockWorkflowClient)(nil).UnpauseTrigger), ctx, workflowID)
}

// DeleteTrigger mocks base method.
func (m *MockWorkflowClient) DeleteTrigger(ctx context.Context, workflowID string, runID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrigger", ctx, workflowID, runID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrigger indicates an expected call of DeleteTrigger.
func (mr *MockWorkflowClientMockRecorder) DeleteTrigger(ctx, workflowID, runID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrigger", reflect.TypeOf((*MockWorkflowClient)(nil).DeleteTrigger), ctx, workflowID, runID)
}

// UpdateTrigger mocks base method.
func (m *MockWorkflowClient) UpdateTrigger(ctx context.Context, workflowID string, newCronSchedule string, paused *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrigger", ctx, workflowID, newCronSchedule, paused)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrigger indicates an expected call of UpdateTrigger.
func (mr *MockWorkflowClientMockRecorder) UpdateTrigger(ctx, workflowID, newCronSchedule, paused interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrigger", reflect.TypeOf((*MockWorkflowClient)(nil).UpdateTrigger), ctx, workflowID, newCronSchedule, paused)
}

// GetTriggerSchedule mocks base method.
func (m *MockWorkflowClient) GetTriggerSchedule(ctx context.Context, workflowID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTriggerSchedule", ctx, workflowID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTriggerSchedule indicates an expected call of GetTriggerSchedule.
func (mr *MockWorkflowClientMockRecorder) GetTriggerSchedule(ctx, workflowID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTriggerSchedule", reflect.TypeOf((*MockWorkflowClient)(nil).GetTriggerSchedule), ctx, workflowID)
}
