CREATE TABLE `test_indexing`
(
    `uid`         VARCHAR(255) NOT NULL,
    `group_ver`   VARCHAR(255) NOT NULL,
    `namespace`   VARCHAR(255) NOT NULL,
    `name`        VARCHAR(255) NOT NULL,
    `res_version` BIGINT UNSIGNED NOT NULL,
    `create_time` DATETIME     NOT NULL,
    `update_time` DATETIME,
    `delete_time` DATETIME,
    `proto`       MEDIUMBLOB,
    `json`        JSON,
    `key01`    VARCHAR(255),
    `key02`    INT,
    `key03`    INT,
    `key04`    BIGINT,
    `key05_namespace`    VARCHAR(255),
    `key05_name`    VARCHAR(255),
    `key06_name`    VARCHAR(255),
    `key06_proxy_user`    VARCHAR(255),
    `key07`    VARCHAR(255),
    `key08`    VARCHAR(255),
    `key09`    BIGINT,
    `key10`    INT,
    `key11`    VARCHAR(255),
    `key12`    BIGINT,
    `key13`    DATETIME,
    `key14`    DATETIME,
    `key15`    VARCHAR(255),
    `key16`    BOOLEAN,
    `key17`    BOOLEAN,
    `key18`    VARCHAR(255),
    `key19`    VARCHAR(768),
    `key20`    VARCHAR(255),
    `key21`    VARCHAR(768),
    PRIMARY KEY   (`uid`),
    KEY    `test_indexing_namespace_name` (`namespace`, `name`),
    KEY    `test_indexing_create_time` (`create_time`),
    KEY    `test_indexing_update_time` (`update_time`),
    KEY    `test_indexing_delete_time` (`delete_time`),
    KEY    `test_indexing_namespace_timestamp` (`namespace`, `delete_time`, `create_time`, `update_time`),
    KEY    `test_indexing_key01` (`key01`),
    KEY    `test_indexing_key02` (`key02`),
    KEY    `test_indexing_key03` (`key03`),
    KEY    `test_indexing_key04` (`key04`),
    KEY    `test_indexing_key05` (`key05_namespace`, `key05_name`),
    KEY    `test_indexing_key06_name` (`key06_name`),
    KEY    `test_indexing_key06_proxy_user` (`key06_proxy_user`),
    KEY    `test_indexing_key07` (`key07`),
    KEY    `test_indexing_key08` (`key08`),
    KEY    `test_indexing_key09` (`key09`),
    KEY    `test_indexing_key10` (`key10`),
    KEY    `test_indexing_key11` (`key11`),
    KEY    `test_indexing_key12` (`key12`),
    KEY    `test_indexing_key13` (`key13`),
    KEY    `test_indexing_key14` (`key14`),
    KEY    `test_indexing_key15` (`key15`),
    KEY    `test_indexing_key16` (`key16`),
    KEY    `test_indexing_key17` (`key17`),
    KEY    `test_indexing_key18` (`key18`),
    KEY    `test_indexing_key19` (`key19`),
    KEY    `test_indexing_key20` (`key20`),
    KEY    `test_indexing_key21` (`key21`)
);
CREATE TABLE `test_indexing_labels`
(
    `id`      BIGINT       NOT NULL AUTO_INCREMENT,
    `obj_uid` VARCHAR(255) NOT NULL,
    `key`     VARCHAR(255) NOT NULL,
    `value`   VARCHAR(63),
    PRIMARY KEY (`id`),
    KEY    `test_indexing_labels_uid` (`obj_uid`),
    KEY    `test_indexing_labels_value` (`key`, `value`)
);
CREATE TABLE `test_indexing_annotations`
(
    `id`      BIGINT       NOT NULL AUTO_INCREMENT,
    `obj_uid` VARCHAR(255) NOT NULL,
    `key`     VARCHAR(255) NOT NULL,
    `value`   TEXT,
    PRIMARY KEY (`id`),
    KEY    `test_indexing_annotations_uid` (`obj_uid`)
);
CREATE TABLE `sample_message_test_indexing_unmarshalled`
(
    `test_indexing_uid` VARCHAR(255) NOT NULL,
    `content_string`    VARCHAR(255),
    `content_int32`    INT,
    `content_long_string`    VARCHAR(768),
    PRIMARY KEY (`test_indexing_uid`),
    KEY    `sample_message_test_indexing_unmarshalled_content_string` (`content_string`),
    KEY    `sample_message_test_indexing_unmarshalled_content_int32` (`content_int32`),
    KEY    `sample_message_test_indexing_unmarshalled_content_long_string` (`content_long_string`)
);
